name: React CI/CD

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm install

      - name: Build da aplicação
        run: npm run build

      - name: Rodar anti-deploy-sexta
        uses: github/codeql-action/init@v4
        with:
          languages: javascript-typescript
      - uses: github/codeql-action/autobuild@v4
      - uses: github/codeql-action/analyze@v4
      
